INSERT INTO `request_tree` VALUES (1,0,'requestRoot',1,1,0,'КОРЕНЬ запроса');
INSERT INTO `request_tree` VALUES (2,1,'question',2,1,0,'Ð’ВОПРОС запроса');
INSERT INTO `request_tree` VALUES (3,1,'subject',3,1,0,'СУБЪЕКТ запроса');
INSERT INTO `request_tree` VALUES (4,1,'action',4,1,0,'Ð”Ð•Ð™Ð¡Ð¢Ð’ДЕЙСТВИЕ запроса');
INSERT INTO `request_tree` VALUES (5,1,'object',5,1,0,'ОБЪЕКТ запроса');
INSERT INTO `request_tree` VALUES (6,2,'where',7,1,0,'вопрос ГДЕ');
INSERT INTO `request_tree` VALUES (7,2,'what',7,1,0,'вопрос ЧТО');
INSERT INTO `request_tree` VALUES (8,2,'why',7,1,0,'вопрос ПОЧЕМУ');
INSERT INTO `request_tree` VALUES (9,2,'when',7,1,0,'вопрос КОГДА');
INSERT INTO `request_tree` VALUES (13,3,'user',7,1,0,'ПОЛЬЗОВАТЕЛЬ - субъект запроса');
INSERT INTO `request_tree` VALUES (14,13,'хочу',8,1,0,'синоним USER');
INSERT INTO `request_tree` VALUES (15,13,'хотелось бы',8,1,0,'синоним USER');
INSERT INTO `request_tree` VALUES (16,13,'покажите',8,1,0,'синоним USER');
INSERT INTO `request_tree` VALUES (17,6,'где',8,1,0,'синоним WHERE');
INSERT INTO `request_tree` VALUES (18,6,'куда',8,1,0,'синоним WHERE');
INSERT INTO `request_tree` VALUES (19,6,'откуда',8,1,0,'синоним WHERE');
INSERT INTO `request_tree` VALUES (20,7,'что',8,1,0,'синоним WHAT');
INSERT INTO `request_tree` VALUES (21,7,'какой',8,1,0,'синоним WHAT');
INSERT INTO `request_tree` VALUES (22,7,'каков',8,1,0,'синоним WHAT');
INSERT INTO `request_tree` VALUES (23,7,'который',8,1,0,'синоним WHAT');
INSERT INTO `request_tree` VALUES (24,8,'почему',8,1,0,'синоним WHY');
INSERT INTO `request_tree` VALUES (25,8,'зачем',8,1,0,'синоним WHY');
INSERT INTO `request_tree` VALUES (26,8,'как',8,1,0,'синоним WHY');
INSERT INTO `request_tree` VALUES (27,9,'когда',8,1,0,'синоним WHEN');
INSERT INTO `request_tree` VALUES (28,9,'укажите дату',8,1,0,'синоним WHEN');
INSERT INTO `request_tree` VALUES (29,4,'buy',7,1,0,'действие КУПИТЬ');
INSERT INTO `request_tree` VALUES (30,4,'look',7,1,0,'действие ПРОСМОТРЕТЬ');
INSERT INTO `request_tree` VALUES (31,4,'order',7,1,0,'действие ЗАКАЗАТЬ');
INSERT INTO `request_tree` VALUES (32,29,'купить',8,1,0,'синоним BUY');
INSERT INTO `request_tree` VALUES (33,29,'приобрести',8,1,0,'синоним BUY');
INSERT INTO `request_tree` VALUES (34,29,'получить',8,1,0,'синоним BUY');
INSERT INTO `request_tree` VALUES (35,30,'узнать',8,1,0,'синоним LOOK');
INSERT INTO `request_tree` VALUES (36,30,'посмотреть',8,1,0,'синоним LOOK');
INSERT INTO `request_tree` VALUES (37,30,'покажите',8,1,0,'синоним LOOK');
INSERT INTO `request_tree` VALUES (38,31,'заказать',8,1,0,'синоним ORDER');
INSERT INTO `request_tree` VALUES (39,31,'заказывать',8,1,0,'синоним ORDER');
INSERT INTO `request_tree` VALUES (40,31,'сделать заказ',8,1,0,'синоним LOOK');
INSERT INTO `request_tree` VALUES (41,29,'купить',8,1,0,'синоним BUY');
INSERT INTO `request_tree` VALUES (42,29,'приобрести',8,1,0,'синоним BUY');
INSERT INTO `request_tree` VALUES (43,29,'получить',8,1,0,'синоним BUY');
INSERT INTO `request_tree` VALUES (44,30,'узнать',8,1,0,'синоним LOOK');
INSERT INTO `request_tree` VALUES (45,30,'посмотреть',8,1,0,'синоним LOOK');
INSERT INTO `request_tree` VALUES (46,30,'покажите',8,1,0,'синоним LOOK');
INSERT INTO `request_tree` VALUES (47,31,'заказать',8,1,0,'синоним ORDER');
INSERT INTO `request_tree` VALUES (48,31,'заказывать',8,1,0,'синоним ORDER');
INSERT INTO `request_tree` VALUES (49,31,'сделать заказ',8,1,0,'синоним ORDER');
INSERT INTO `request_tree` VALUES (50,5,'price',7,1,0,'ЦЕНА');
INSERT INTO `request_tree` VALUES (51,5,'repairman',7,1,0,'МАСТЕР');
INSERT INTO `request_tree` VALUES (52,5,'product',6,1,0,'под-объект ПРОДУКТ, ИЗДЕЛИЕ');
INSERT INTO `request_tree` VALUES (53,5,'service',6,1,0,'под-объект УСЛУГИ');
INSERT INTO `request_tree` VALUES (67,50,'цена',8,1,0,'синоним PRICE');
INSERT INTO `request_tree` VALUES (68,50,'цены',8,1,0,'синоним PRICE');
INSERT INTO `request_tree` VALUES (69,50,'ценами',8,1,0,'синоним PRICE');
INSERT INTO `request_tree` VALUES (70,50,'по цене',8,1,0,'синоним PRICE');
INSERT INTO `request_tree` VALUES (71,50,'по какой цене',8,1,0,'синоним PRICE');
INSERT INTO `request_tree` VALUES (72,50,'сколько стоит‚',8,1,0,'синоним PRICE');
INSERT INTO `request_tree` VALUES (73,50,'стоимость',8,1,0,'синоним PRICE');
INSERT INTO `request_tree` VALUES (74,51,'мастер по ремонту',8,1,0,'синоним REPAIRMAN');
INSERT INTO `request_tree` VALUES (75,51,'специалист по ремнту',8,1,0,'синоним REPAIRMAN');
INSERT INTO `request_tree` VALUES (76,51,'элекрик',8,1,0,'синоним REPAIRMAN');
INSERT INTO `request_tree` VALUES (77,51,'сантехник',8,1,0,'синоним REPAIRMAN');
INSERT INTO `request_tree` VALUES (89,5,'place',6,1,0,'под-объект МЕСТО выполнения запроса(город,..)');
INSERT INTO `request_tree` VALUES (90,52,'fridge',7,1,0,'ХОЛОДИЛЬНИК');
INSERT INTO `request_tree` VALUES (92,52,'washer',7,1,0,'СТИРАЛЬНАЯ МАШИНА');
