INSERT INTO thoughts (text) VALUES ('ДА') ;
INSERT INTO thoughts (text) VALUES ('НЕТ') ;
INSERT INTO thoughts (text) VALUES ('Может быть') ;
INSERT INTO thoughts (text) VALUES ('Возможно') ;
INSERT INTO thoughts (text) VALUES ('Не сейчас') ;
INSERT INTO thoughts (text) VALUES ('Может, стоит подумать?') ;
INSERT INTO thoughts (text) VALUES ('Вернее всего «Да»') ;
INSERT INTO thoughts (text) VALUES ('Вернее всего «Нет»') ;
INSERT INTO thoughts (text) VALUES ('Если вы так решили, то «Да»') ;
INSERT INTO thoughts (text) VALUES ('Если вы сомневаетесь, то «Нет»') ;
INSERT INTO thoughts (text) VALUES ('Сегодня на этот вопрос нет ответа') ;
INSERT INTO thoughts (text) VALUES ('Попробуйте обратиться за советом к другу') ;
INSERT INTO thoughts (text) VALUES ('Не всё получается, так как мы хотим') ;
INSERT INTO thoughts (text) VALUES ('Вы думаете в правильном направлении') ;
INSERT INTO thoughts (text) VALUES ('Как вы захотите, так и будет') ;
INSERT INTO thoughts (text) VALUES ('Надо приложить максимум усилий') ;
INSERT INTO thoughts (text) VALUES ('Звезды сегодня на вашей стороне') ;
INSERT INTO thoughts (text) VALUES ('Скорее «Да», чем «Нет»') ;
INSERT INTO thoughts (text) VALUES ('Скорее «Нет», чем «Да»') ;
INSERT INTO thoughts (text) VALUES ('Перенесите решение этого вопроса на некоторое время') ;
INSERT INTO thoughts (text) VALUES ('Сегодня это не основной ваш вопрос') ;
INSERT INTO thoughts (text) VALUES ('Может, стоит сегодня подумать о более важном?') ;
INSERT INTO thoughts (text) VALUES ('Вы сами найдете ответ на этот вопрос через некоторое время') ;
INSERT INTO thoughts (text) VALUES ('Не делайте то, о чем думаете') ;
INSERT INTO thoughts (text) VALUES ('Это только ваши фантазии') ;
INSERT INTO thoughts (text) VALUES ('Иногда мечты воплощаются в жизнь') ;
INSERT INTO thoughts (text) VALUES ('Вы на правильном пути') ;
INSERT INTO thoughts (text) VALUES ('Если вы себе в чем то откажите, то «Да»') ;
INSERT INTO thoughts (text) VALUES ('Возможно, но для этого надо многое сделать') ;
INSERT INTO thoughts (text) VALUES ('Вам придется самому принимать решение') ;
INSERT INTO thoughts (text) VALUES ('Спросите у близкого человека «Да или Нет», то что он ответит и будет ответом на ваш вопрос') ;
INSERT INTO thoughts (text) VALUES ('Еще раз все обдумайте') ;
INSERT INTO thoughts (text) VALUES ('Подумайте о последствиях вашего решения') ;
INSERT INTO thoughts (text) VALUES ('Вам придется потрудиться') ;
INSERT INTO thoughts (text) VALUES ('Ни что не дается просто так') ;
INSERT INTO thoughts (text) VALUES ('Откройте вашу любимую книгу на 37 странице, третий абзац сверху – прочитайте и все станет понятно. (страницы должны меняться от 17 до 77, все с цифрой 7 на конце) (абзацы тоже, с первого по пятый)';
INSERT INTO thoughts (text) VALUES ('Сложно дать однозначный ответ – обратитесь к Оракулу.');
INSERT INTO thoughts (text) VALUES ('Для этого придется чем-то пожертвовать') ;
INSERT INTO thoughts (text) VALUES ('Есть шанс') ;
INSERT INTO thoughts (text) VALUES ('Скоро');
INSERT INTO thoughts (text) VALUES ('Не сейчас');
INSERT INTO thoughts (text) VALUES ('Почему бы и нет.') ;
INSERT INTO thoughts (text) VALUES ('Если бы вас об этом спросили, что вы бы ответили?') ;
INSERT INTO thoughts (text) VALUES ('Сегодня все в ваших руках') ;
INSERT INTO thoughts (text) VALUES ('Подкиньте монетку на «Орел» или «Решку»') ;
INSERT INTO thoughts (text) VALUES ('Если сейчас чистое небо, то «Да», если в тучах то «Нет»') ;
INSERT INTO thoughts (text) VALUES ('Спросите «Да или Нет» у первого человека которого увидите') ;
INSERT INTO thoughts (text) VALUES ('Сейчас «Да», но все может измениться') ;
INSERT INTO thoughts (text) VALUES ('Сейчас «Нет», но все может поменяться') ;
INSERT INTO thoughts (text) VALUES ('Вам это не поможет') ;
